// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillUp.API.Data;

#nullable disable

namespace SkillUp.API.Migrations
{
    [DbContext(typeof(SkillUpDbContext))]
    [Migration("20251115184307_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("SkillUp.API.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 15, 18, 43, 7, 112, DateTimeKind.Utc).AddTicks(6775),
                            Description = "Curso introdutório sobre Inteligência Artificial",
                            Duration = 40,
                            Instructor = "Dr. João Silva",
                            Price = 299.99m,
                            Title = "Fundamentos de IA"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 15, 18, 43, 7, 112, DateTimeKind.Utc).AddTicks(6777),
                            Description = "Curso completo sobre Amazon Web Services",
                            Duration = 60,
                            Instructor = "Maria Santos",
                            Price = 399.99m,
                            Title = "AWS Essentials"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 15, 18, 43, 7, 112, DateTimeKind.Utc).AddTicks(6778),
                            Description = "Análise de dados usando Python e Pandas",
                            Duration = 50,
                            Instructor = "Carlos Oliveira",
                            Price = 349.99m,
                            Title = "Data Science com Python"
                        });
                });

            modelBuilder.Entity("SkillUp.API.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Tecnologia",
                            CreatedAt = new DateTime(2025, 11, 15, 18, 43, 7, 112, DateTimeKind.Utc).AddTicks(6636),
                            Description = "Conhecimento em IA e Machine Learning",
                            Name = "Inteligência Artificial"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Tecnologia",
                            CreatedAt = new DateTime(2025, 11, 15, 18, 43, 7, 112, DateTimeKind.Utc).AddTicks(6637),
                            Description = "Habilidades em serviços de nuvem (AWS, Azure, GCP)",
                            Name = "Cloud Computing"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Tecnologia",
                            CreatedAt = new DateTime(2025, 11, 15, 18, 43, 7, 112, DateTimeKind.Utc).AddTicks(6638),
                            Description = "Análise de dados e estatística",
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Gestão",
                            CreatedAt = new DateTime(2025, 11, 15, 18, 43, 7, 112, DateTimeKind.Utc).AddTicks(6639),
                            Description = "Gestão de equipes em metodologias ágeis",
                            Name = "Liderança Ágil"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Soft Skills",
                            CreatedAt = new DateTime(2025, 11, 15, 18, 43, 7, 112, DateTimeKind.Utc).AddTicks(6640),
                            Description = "Habilidades de comunicação em ambientes digitais",
                            Name = "Comunicação Digital"
                        });
                });

            modelBuilder.Entity("SkillUp.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SkillUp.API.Models.UserSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProficiencyLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId", "SkillId")
                        .IsUnique();

                    b.ToTable("UserSkills");
                });

            modelBuilder.Entity("SkillUp.API.Models.UserSkill", b =>
                {
                    b.HasOne("SkillUp.API.Models.Skill", "Skill")
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillUp.API.Models.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillUp.API.Models.Skill", b =>
                {
                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("SkillUp.API.Models.User", b =>
                {
                    b.Navigation("UserSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
